kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image }}:{{ .Values.nginx.tag }}
        ports:
        - containerPort: {{ .Values.nginx.port }}
        resources:
          requests:
            memory: {{ .Values.nginx.resourceRequests.mem }}
            cpu: {{ .Values.nginx.resourceRequests.cpu }}
        volumeMounts:
        - name: {{ .Release.Name }}-index-html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: {{ .Release.Name }}-index-html-volume
        configMap:
          name: {{ .Release.Name }}-index-html
