# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: lab

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: |
    # docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.6.6 /repo
    mkdir helm-root
    cd helm-root
    repo_uri=$(git remote get-url origin)
    repo_name=$(basename -s .git $repo_uri)
    
    echo "klonuje $repo_uri"
    git clone -b helm-repo $repo_uri
    ls -la
  displayName: 'Run gitversion'

