apiVersion: v1
entries:
  nginx-helm:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2023-10-21T14:14:51.750692+02:00"
    description: A Helm chart for deploying a nginx application.
    digest: b6a35db10114351a1097e18291b2e162e5f1eedacb92821817a23e6b44b40b10
    name: nginx-helm
    type: application
    urls:
    - nginx-helm-1.0.0.tgz
    version: 1.0.0
generated: "2023-10-21T14:14:51.750303+02:00"
